name: Build and Push Docker Image

on:
  push:
    branches:
    - gateway  # ou le nom de votre branche principale
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
      
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '14'  # Choisissez la version de Node.js que vous souhaitez utiliser
      
        - name: Build Docker Image
          run: docker build -t devops_petclinic_1 .     
        - name: Authenticate to Amazon ECR Public
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: eu-west-3
            run: aws ecr-public get-login-password --region eu-west-3 | docker login --username AWS --password-stdin public.ecr.aws/h7a4i4a9

        - name: Tag Docker Image
          run: docker tag devops_petclinic_1:latest public.ecr.aws/h7a4i4a9/devops_petclinic_1:latest

        - name: Push Docker Image to Amazon ECR Public
          run: docker push public.ecr.aws/h7a4i4a9/devops_petclinic_1:latest
      